### ISSUE TITLE
autogen error

### ISSUE THREAD

**Issue by or78rXxZ** [stealthylabs/libssd1306#1]
~/libssd1306$ ./autogen.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:22: installing './compile'
configure.ac:24: installing './config.guess'
configure.ac:24: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
examples/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
configure.ac:37: error: possibly undefined macro: AC_CHECK_HEADERS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:69: error: possibly undefined macro: AC_DEFINE
configure.ac:109: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:128: error: possibly undefined macro: AC_CHECK_LIB

**Comment by or78rXxZ** [comment]
found the problem
apt install pkg-config
maybe add this to readme

**Comment by stealthylabs** [comment]
Thanks. I have added that to the README.
