### ISSUE TITLE
error make code with raspberrypi x64 lite os

### ISSUE THREAD

**Issue by LD-Geek** [stealthylabs/libssd1306#4]
# make
Making all in src
make[1]: Entering directory '/home/pi/ssd1306/libssd1306/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include    -I/usr/include/freetype2 -I/usr/include/libpng16  -pthread -MT libssd1306_i2c_la-ssd1306_i2c.lo -MD -MP -MF .deps/libssd1306_i2c_la-ssd1306_i2c.Tpo -c -o libssd1306_i2c_la-ssd1306_i2c.lo `test -f 'ssd1306_i2c.c' || echo './'`ssd1306_i2c.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -MT libssd1306_i2c_la-ssd1306_i2c.lo -MD -MP -MF .deps/libssd1306_i2c_la-ssd1306_i2c.Tpo -c ssd1306_i2c.c  -fPIC -DPIC -o .libs/libssd1306_i2c_la-ssd1306_i2c.o
mv -f .deps/libssd1306_i2c_la-ssd1306_i2c.Tpo .deps/libssd1306_i2c_la-ssd1306_i2c.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include    -I/usr/include/freetype2 -I/usr/include/libpng16  -pthread -MT libssd1306_i2c_la-graphics.lo -MD -MP -MF .deps/libssd1306_i2c_la-graphics.Tpo -c -o libssd1306_i2c_la-graphics.lo `test -f 'graphics.c' || echo './'`graphics.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -MT libssd1306_i2c_la-graphics.lo -MD -MP -MF .deps/libssd1306_i2c_la-graphics.Tpo -c graphics.c  -fPIC -DPIC -o .libs/libssd1306_i2c_la-graphics.o
mv -f .deps/libssd1306_i2c_la-graphics.Tpo .deps/libssd1306_i2c_la-graphics.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I/usr/include/freetype2 -I/usr/include/libpng16  -pthread -shared -version-info 0:3:0 -L.. -L. -lfreetype -lunistring  -o libssd1306_i2c.la -rpath /usr/local/lib  libssd1306_i2c_la-ssd1306_i2c.lo libssd1306_i2c_la-graphics.lo  -lpthread 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libssd1306_i2c_la-ssd1306_i2c.o .libs/libssd1306_i2c_la-graphics.o   -L.. -L. -lfreetype -lunistring -lpthread  -pthread   -pthread -Wl,-soname -Wl,libssd1306_i2c.so.0 -o .libs/libssd1306_i2c.so.0.0.3
libtool: link: (cd ".libs" && rm -f "libssd1306_i2c.so.0" && ln -s "libssd1306_i2c.so.0.0.3" "libssd1306_i2c.so.0")
libtool: link: (cd ".libs" && rm -f "libssd1306_i2c.so" && ln -s "libssd1306_i2c.so.0.0.3" "libssd1306_i2c.so")
libtool: link: ( cd ".libs" && rm -f "libssd1306_i2c.la" && ln -s "../libssd1306_i2c.la" "libssd1306_i2c.la" )
make[1]: Leaving directory '/home/pi/ssd1306/libssd1306/src'
Making all in examples
make[1]: Entering directory '/home/pi/ssd1306/libssd1306/examples'
depbase=`echo i2c_128x32_graphics.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../include    -Wall -Wextra -Wno-uninitialized -fPIC -pedantic -posix -std=c11 -D_DEFAULT_SOURCE -D_REENTRANT -pthread -MT i2c_128x32_graphics.o -MD -MP -MF $depbase.Tpo -c -o i2c_128x32_graphics.o i2c_128x32_graphics.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc: error: unrecognized command-line option ‘-posix’
make[1]: *** [Makefile:638: i2c_128x32_graphics.o] Error 1
make[1]: Leaving directory '/home/pi/ssd1306/libssd1306/examples'
make: *** [Makefile:413: all-recursive] Error 1

**Comment by LD-Geek** [comment]
> 
libssd1306/examples/Makefile
remove line 418 the option -posix 
it works well in raspberry pi x64 lite os.

**Comment by stealthylabs** [comment]
Done.
